os:
  - linux

sudo: false

language: go

go:
    - 1.10.0

install:
  - make deps

script:
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
